create extension if not exists pgcrypto;

create table if not exists public.orders (
    id uuid primary key default gen_random_uuid(),
    order_number text unique not null,
    customer_name text not null,
    phone text not null,
    address text not null,
    notes text,
    payment_method text not null default 'cash',
    total numeric not null default 0 check (total >= 0),
    status text not null default 'new' check (status in ('new', 'accepted', 'preparing', 'delivering', 'delivered', 'cancelled')),
    created_at timestamptz not null default now()
);

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,
    order_id uuid not null references public.orders(id) on delete cascade,
    product_name text not null,
    size text not null,
    quantity integer not null check (quantity between 1 and 20),
    unit_price numeric not null check (unit_price >= 0),
    total_price numeric not null check (total_price >= 0)
);

create table if not exists public.admin_users (
    user_id uuid primary key references auth.users(id) on delete cascade
);

-- بعد إنشاء مستخدم المدير من Authentication > Users،
-- استبدل UUID التالي بمعرّف المستخدم وشغّل السطر:
-- insert into public.admin_users (user_id) values ('USER_UUID_HERE');
insert into public.admin_users (user_id)
values ('f4e58620-0a40-4a60-9e59-4f00785cc484')
on conflict (user_id) do nothing;

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.admin_users where user_id = auth.uid()
    );
$$;

revoke all on public.orders from anon, authenticated;
revoke all on public.order_items from anon, authenticated;
revoke all on public.admin_users from anon, authenticated;
grant usage on schema public to anon, authenticated;
grant select, update, delete on public.orders to authenticated;
grant select on public.order_items to authenticated;

drop policy if exists "Anyone can create orders" on public.orders;
drop policy if exists "Anyone can create order items" on public.order_items;
drop policy if exists "Anyone can read orders" on public.orders;
drop policy if exists "Anyone can read order items" on public.order_items;
drop policy if exists "Anyone can update order status" on public.orders;
drop policy if exists "Admins can read orders" on public.orders;
drop policy if exists "Admins can read order items" on public.order_items;
drop policy if exists "Admins can update orders" on public.orders;
drop policy if exists "Admins can delete orders" on public.orders;

create policy "Admins can read orders"
on public.orders for select to authenticated
using (public.is_admin());

create policy "Admins can read order items"
on public.order_items for select to authenticated
using (public.is_admin());

create policy "Admins can update orders"
on public.orders for update to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete orders"
on public.orders for delete to authenticated
using (public.is_admin());

create or replace function public.create_order(order_data jsonb, items_data jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
    new_order_id uuid;
begin
    if jsonb_array_length(items_data) = 0 then
        raise exception 'Order must contain at least one item';
    end if;

    insert into public.orders (
        order_number, customer_name, phone, address, notes, payment_method, total, status
    ) values (
        order_data->>'order_number',
        left(trim(order_data->>'customer_name'), 120),
        left(trim(order_data->>'phone'), 40),
        left(trim(order_data->>'address'), 500),
        left(coalesce(order_data->>'notes', ''), 1000),
        case when order_data->>'payment_method' = 'transfer' then 'transfer' else 'cash' end,
        greatest((order_data->>'total')::numeric, 0),
        'new'
    )
    returning id into new_order_id;

    insert into public.order_items (order_id, product_name, size, quantity, unit_price, total_price)
    select
        new_order_id,
        left(item->>'product_name', 120),
        left(item->>'size', 30),
        least(greatest((item->>'quantity')::integer, 1), 20),
        greatest((item->>'unit_price')::numeric, 0),
        greatest((item->>'total_price')::numeric, 0)
    from jsonb_array_elements(items_data) as item;

    return new_order_id;
end;
$$;

grant execute on function public.create_order(jsonb, jsonb) to anon, authenticated;
